const mockData = {
  page: 7,
  results: [
    {
      adult: false,
      backdrop_path: "/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg",
      genre_ids: [18, 36],
      id: 906126,
      original_language: "es",
      original_title: "La sociedad de la nieve",
      overview:
        "On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.",
      popularity: 170.642,
      poster_path: "/k7rEpZfNPB35FFHB00ZhXHKTL7X.jpg",
      release_date: "2023-12-15",
      title: "Society of the Snow",
      video: false,
      vote_average: 8.3,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/zRQITMLvVi8z2Xz12Bi6wvbZE82.jpg",
      genre_ids: [35, 28, 14],
      id: 594767,
      original_language: "en",
      original_title: "Shazam! Fury of the Gods",
      overview:
        'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
      popularity: 170.414,
      poster_path: "/A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg",
      release_date: "2023-03-15",
      title: "Shazam! Fury of the Gods",
      video: false,
      vote_average: 6.6,
      vote_count: 2649,
    },
    {
      adult: false,
      backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
      genre_ids: [28, 12, 878],
      id: 505642,
      original_language: "en",
      original_title: "Black Panther: Wakanda Forever",
      overview:
        "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
      popularity: 167.906,
      poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
      release_date: "2022-11-09",
      title: "Black Panther: Wakanda Forever",
      video: false,
      vote_average: 7.2,
      vote_count: 5779,
    },
    {
      adult: false,
      backdrop_path: "/bVmSXNgH1gpHYTDyF9Q826YwJT5.jpg",
      genre_ids: [28, 12, 14],
      id: 122917,
      original_language: "en",
      original_title: "The Hobbit: The Battle of the Five Armies",
      overview:
        "Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.",
      popularity: 167.723,
      poster_path: "/xT98tLqatZPQApyRmlPL12LtiWp.jpg",
      release_date: "2014-12-10",
      title: "The Hobbit: The Battle of the Five Armies",
      video: false,
      vote_average: 7.3,
      vote_count: 13509,
    },
    {
      adult: false,
      backdrop_path: "/8g9ZdvHX6jszRY71aVtpRUmHQzJ.jpg",
      genre_ids: [18, 53],
      id: 958182,
      original_language: "es",
      original_title: "Heroico",
      overview:
        "Luis, an 18-year-old boy with Indigenous roots, enters the Heroic Military College in hopes of ensuring a better future. There, he encounters a rigid and institutionally violent system designed to turn him into a perfect soldier.",
      popularity: 165.833,
      poster_path: "/tRD18JW9iKqmwkQKvzPYDQetRoI.jpg",
      release_date: "2023-09-21",
      title: "Heroic",
      video: false,
      vote_average: 7.5,
      vote_count: 87,
    },
    {
      adult: false,
      backdrop_path: "/1Ei7klVVpCpGCko616FPRuAlFUC.jpg",
      genre_ids: [28, 9648, 53, 27],
      id: 1006462,
      original_language: "en",
      original_title: "The Flood",
      overview:
        "A horde of giant hungry alligators is unleashed on a group of in-transit prisoners and their guards after a massive hurricane floods Louisiana.",
      popularity: 164.875,
      poster_path: "/mvjqqklMpHwOxc40rn7dMhGT0Fc.jpg",
      release_date: "2023-07-14",
      title: "The Flood",
      video: false,
      vote_average: 6.7,
      vote_count: 222,
    },
    {
      adult: false,
      backdrop_path: "/rrucFNW1qOgSPL4n2Fy6CdpBDEY.jpg",
      genre_ids: [27, 35, 53],
      id: 1161048,
      original_language: "sv",
      original_title: "Konferensen",
      overview:
        "A team-building conference for municipal employees turns into a nightmare when accusations of corruption begin to circulate and plague the work environment. At the same time, a mysterious figure begins murdering the participants.",
      popularity: 164.599,
      poster_path: "/uLH5rUkRNwAUt6YqR86f8ewXZEY.jpg",
      release_date: "2023-10-13",
      title: "The Conference",
      video: false,
      vote_average: 5.4,
      vote_count: 229,
    },
    {
      adult: false,
      backdrop_path: "/5rrGVmRUuCKVbqUu41XIWTXJmNA.jpg",
      genre_ids: [12, 14],
      id: 674,
      original_language: "en",
      original_title: "Harry Potter and the Goblet of Fire",
      overview:
        "When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools—the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named.",
      popularity: 164.475,
      poster_path: "/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg",
      release_date: "2005-11-16",
      title: "Harry Potter and the Goblet of Fire",
      video: false,
      vote_average: 7.8,
      vote_count: 19640,
    },
    {
      adult: false,
      backdrop_path: "/bGQyu8H6q20ZRxqr3z65kE17QPA.jpg",
      genre_ids: [28, 53],
      id: 1171541,
      original_language: "en",
      original_title: "Sniper: G.R.I.T. - Global Response & Intelligence Team",
      overview:
        "When an international terrorist cult threatens global political stability and kidnaps a fellow agent, Ace Sniper Brandon Beckett and the newly-formed Global Response & Intelligence Team – or G.R.I.T. – led by Colonel Stone must travel across the world to Malta, infiltrate the cult, and take out its leader to free Lady Death and stop the global threat.",
      popularity: 163.654,
      poster_path: "/a9bt9byTQ1MIfRWYQX240HiYPrl.jpg",
      release_date: "2023-09-26",
      title: "Sniper: G.R.I.T. - Global Response & Intelligence Team",
      video: false,
      vote_average: 6.8,
      vote_count: 93,
    },
    {
      adult: false,
      backdrop_path: "/uSUjIzqKyebAd2wqDyb11Ya4wch.jpg",
      genre_ids: [28, 10752],
      id: 1062482,
      original_language: "en",
      original_title: "Condor's Nest",
      overview:
        "American war veteran Will Spalding has tracked the sadistic Nazi Colonel who executed his bomber crew during WWII to a remote location in South America. But he is in for more than he bargained for when he uncovers a secret Nazi headquarters known as the Condor's Nest.",
      popularity: 163.283,
      poster_path: "/aBAsCMzsbGlFtQFqeWsKWM6hvOE.jpg",
      release_date: "2023-01-27",
      title: "Condor's Nest",
      video: false,
      vote_average: 5.7,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/AqgFkAcZjxr6x8TXHx4StaKr7t1.jpg",
      genre_ids: [28, 12, 16, 35, 10751],
      id: 1011985,
      original_language: "en",
      original_title: "Kung Fu Panda 4",
      overview:
        "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
      popularity: 163.258,
      poster_path: "/v77WjVsTMPKTpXZoW2RVNegappO.jpg",
      release_date: "2024-03-06",
      title: "Kung Fu Panda 4",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
      genre_ids: [12, 14],
      id: 767,
      original_language: "en",
      original_title: "Harry Potter and the Half-Blood Prince",
      overview:
        "As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
      popularity: 162.952,
      poster_path: "/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
      release_date: "2009-07-15",
      title: "Harry Potter and the Half-Blood Prince",
      video: false,
      vote_average: 7.7,
      vote_count: 18433,
    },
    {
      adult: false,
      backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
      genre_ids: [28, 878, 53],
      id: 399566,
      original_language: "en",
      original_title: "Godzilla vs. Kong",
      overview:
        "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
      popularity: 162.37,
      poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
      release_date: "2021-03-24",
      title: "Godzilla vs. Kong",
      video: false,
      vote_average: 7.6,
      vote_count: 9273,
    },
    {
      adult: false,
      backdrop_path: "/efro4duB7agkA2Xl5LmkD3HeCim.jpg",
      genre_ids: [28, 53, 18],
      id: 818511,
      original_language: "pt",
      original_title: "Carga Máxima",
      overview:
        "When truck racer Roger loses everything, he receives a tempting but dangerous offer: to work as the getaway driver for a gang of thieves.",
      popularity: 162.127,
      poster_path: "/6yx14lSACNJ2zRoYyXqecf3QNgr.jpg",
      release_date: "2023-09-27",
      title: "Overhaul",
      video: false,
      vote_average: 6.7,
      vote_count: 108,
    },
    {
      adult: false,
      backdrop_path: "/8RBwd37p2p48lUmZuWBLSkFLprd.jpg",
      genre_ids: [27, 35],
      id: 1113278,
      original_language: "en",
      original_title: "It's a Wonderful Knife",
      overview:
        "Winnie's life is less than wonderful one year after saving her town from a psychotic killer on Christmas Eve. When she wishes she was never born, she finds herself magically transported to a nightmarish parallel universe. With the murderous maniac now back, she must team up with a misfit to identify the culprit and get back to her own reality.",
      popularity: 161.469,
      poster_path: "/qToCVGHgu1670jZKjbdUnMVKmPc.jpg",
      release_date: "2023-11-10",
      title: "It's a Wonderful Knife",
      video: false,
      vote_average: 5.3,
      vote_count: 55,
    },
    {
      adult: false,
      backdrop_path: "/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
      genre_ids: [27, 80, 53],
      id: 934433,
      original_language: "en",
      original_title: "Scream VI",
      overview:
        "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
      popularity: 161.326,
      poster_path: "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
      release_date: "2023-03-08",
      title: "Scream VI",
      video: false,
      vote_average: 7.1,
      vote_count: 2146,
    },
    {
      adult: false,
      backdrop_path: "/bSvUW4JQ6g4QiKvwejcfcPRd4Ke.jpg",
      genre_ids: [12, 35, 10751, 14],
      id: 118,
      original_language: "en",
      original_title: "Charlie and the Chocolate Factory",
      overview:
        "A young boy wins a tour through the most magnificent chocolate factory in the world, led by the world's most unusual candy maker.",
      popularity: 161.249,
      poster_path: "/wfGfxtBkhBzQfOZw4S8IQZgrH0a.jpg",
      release_date: "2005-07-13",
      title: "Charlie and the Chocolate Factory",
      video: false,
      vote_average: 7,
      vote_count: 14298,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18, 10749],
      id: 1156593,
      original_language: "es",
      original_title: "Culpa tuya",
      overview: "",
      popularity: 160.846,
      poster_path: "/3pkjbiL9ju2VdLohIGW4NOYkASi.jpg",
      title: "Your Fault",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/jBOyi3ibJbVa1imTCcddPUxTVAV.jpg",
      genre_ids: [35, 27, 14],
      id: 956920,
      original_language: "no",
      original_title: "There's Something in the Barn",
      overview:
        "An American family fulfills their dream of moving back to their roots after inheriting a remote cabin in the mountains of Norway. But there's a surprise waiting for them.",
      popularity: 160.742,
      poster_path: "/8qSov4Y66aXtMSQoVh4iEi5wLnd.jpg",
      release_date: "2023-11-02",
      title: "There's Something in the Barn",
      video: false,
      vote_average: 6.7,
      vote_count: 83,
    },
    {
      adult: false,
      backdrop_path: "/nmly11JCqU9WhbjYwKWXoWDsCgI.jpg",
      genre_ids: [80, 18, 9648],
      id: 10367,
      original_language: "en",
      original_title: "Wild Things 2",
      overview:
        "Two Florida high school vixens hatch a murderous plan to win an inheritance, but they hadn't bargained for an escalating whirlpool of blackmail and sexual games with a sleazy insurance investigator who has his own plans for the money.",
      popularity: 160.62,
      poster_path: "/3aoRiK4Q36kS4kYWWeF1CG4HhZr.jpg",
      release_date: "2004-02-19",
      title: "Wild Things 2",
      video: false,
      vote_average: 5.1,
      vote_count: 173,
    },
  ],
  total_pages: 41769,
  total_results: 835363,
};
export default mockData;
